
exports.up = function (knex, Promise) {
  return knex.schema.createTable('communes', function (table) {
    table.increments('id').primary();
    table.integer('arrondissement_id').unsigned();
    table.string('name', 100).notNullable();
    table.string('description', 250);

    table.datetime('created_at').defaultTo(knex.fn.now());
    table.datetime('updated_at').defaultTo(knex.fn.now());

    table.foreign('arrondissement_id').references('arrondissements.id').onUpdate('CASCADE').onDelete('RESTRICT');
  }).then(() => knex('communes').insert([
    { arrondissement_id: 1, name: 'Dessalines' },
    { arrondissement_id: 1, name: 'Desdune' },
    { arrondissement_id: 1, name: 'Grande-Saline' },
    { arrondissement_id: 1, name: 'Petite Rivière de l\'Artibonite' },
    { arrondissement_id: 2, name: 'Gonaïves' },
    { arrondissement_id: 2, name: 'Ennery' },
    { arrondissement_id: 2, name: 'l\'Estère' },
    { arrondissement_id: 3, name: 'Gros-Morne' },
    { arrondissement_id: 3, name: 'Anse-Rouge' },
    { arrondissement_id: 3, name: 'Terre-Neuve' },
    { arrondissement_id: 4, name: 'Marmelade' },
    { arrondissement_id: 4, name: 'Saint-Michel-de-l\'Atalaye' },
    { arrondissement_id: 5, name: 'Saint-Marc' },
    { arrondissement_id: 5, name: 'La Chappelle' },
    { arrondissement_id: 5, name: 'Liancourt' },
    { arrondissement_id: 5, name: 'Verrettes' },
    { arrondissement_id: 6, name: 'Cerca-la-Source ' },
    { arrondissement_id: 6, name: 'Thomassique' },
    { arrondissement_id: 7, name: 'Hinche' },
    { arrondissement_id: 7, name: 'Cerca-Carvajal' },
    { arrondissement_id: 7, name: 'Maïssade' },
    { arrondissement_id: 7, name: 'Thomonde' },
    { arrondissement_id: 8, name: 'Lascahobas' },
    { arrondissement_id: 8, name: 'Baptiste' },
    { arrondissement_id: 8, name: 'Belladère' },
    { arrondissement_id: 8, name: 'Savanette' },
    { arrondissement_id: 9, name: 'Mirebalais' },
    { arrondissement_id: 9, name: 'Boucan-Carré' },
    { arrondissement_id: 9, name: 'Saut-d\'Eau' },
    { arrondissement_id: 10, name: 'Anse d\'Hainault' },
    { arrondissement_id: 10, name: 'Dame-Marie' },
    { arrondissement_id: 10, name: 'Les Irois' },
    { arrondissement_id: 11, name: 'Beaumont' },
    { arrondissement_id: 11, name: 'Corail' },
    { arrondissement_id: 11, name: 'Pestel' },
    { arrondissement_id: 11, name: 'Roseaux' },
    { arrondissement_id: 12, name: 'Jérémie' },
    { arrondissement_id: 12, name: 'Abricot' },
    { arrondissement_id: 12, name: 'BonBon' },
    { arrondissement_id: 12, name: 'Chambellan' },
    { arrondissement_id: 12, name: 'Marfranc' },
    { arrondissement_id: 12, name: 'Moron' },
    { arrondissement_id: 13, name: 'Anse-à-Veau' },
    { arrondissement_id: 13, name: 'Arnaud' },
    { arrondissement_id: 13, name: 'L\'Asile' },
    { arrondissement_id: 13, name: 'Peti-Trou-de-Nippes' },
    { arrondissement_id: 13, name: 'Plaisance-du-Sud' },
    { arrondissement_id: 14, name: 'Baradères' },
    { arrondissement_id: 14, name: 'Grand-Boucan' },
    { arrondissement_id: 15, name: 'Miragoâne' },
    { arrondissement_id: 15, name: 'Fonds-des-Nègres' },
    { arrondissement_id: 15, name: 'Paillant' },
    { arrondissement_id: 15, name: 'Petite-Rivière-de-Nippes' },
    { arrondissement_id: 16, name: 'Acul-du-Nord' },
    { arrondissement_id: 16, name: 'Milot' },
    { arrondissement_id: 16, name: 'Plaine-du-Nord' },
    { arrondissement_id: 17, name: 'Borgne' },
    { arrondissement_id: 17, name: 'Port-Margot' },
    { arrondissement_id: 18, name: 'Cap-Haïtien' },
    { arrondissement_id: 18, name: 'Limonade' },
    { arrondissement_id: 18, name: 'Quartier-Morin' },
    { arrondissement_id: 19, name: 'Grande-Rivière-du-Nord' },
    { arrondissement_id: 19, name: 'Bahon' },
    { arrondissement_id: 20, name: 'Limbé' },
    { arrondissement_id: 20, name: 'Bas-Limbé' },
    { arrondissement_id: 21, name: 'Plaissance' },
    { arrondissement_id: 21, name: 'Pilate' },
    { arrondissement_id: 22, name: 'Saint-Raphaêle' },
    { arrondissement_id: 22, name: 'Dondon' },
    { arrondissement_id: 22, name: 'La Victoire' },
    { arrondissement_id: 22, name: 'Pignon' },
    { arrondissement_id: 22, name: 'Ranquitte' },
    { arrondissement_id: 23, name: 'Fort-Liberté' },
    { arrondissement_id: 23, name: 'Perches' },
    { arrondissement_id: 23, name: 'Ferrier' },
    { arrondissement_id: 24, name: 'Ouanaminthe' },
    { arrondissement_id: 24, name: 'Capotille' },
    { arrondissement_id: 24, name: 'Mont-Organisé' },
    { arrondissement_id: 25, name: 'Trou-du-Nord' },
    { arrondissement_id: 25, name: 'Caracol' },
    { arrondissement_id: 25, name: 'Sainte-Suzanne' },
    { arrondissement_id: 25, name: 'Grand-Bassin' },
    { arrondissement_id: 26, name: 'Vallières' },
    { arrondissement_id: 26, name: 'Carice' },
    { arrondissement_id: 26, name: 'Mombin-Crochu' },
    { arrondissement_id: 27, name: 'Môle-Saint-Nicolas' },
    { arrondissement_id: 27, name: 'Baie-de-Henne' },
    { arrondissement_id: 27, name: 'Bombardopolis' },
    { arrondissement_id: 27, name: 'Jean-Raphaël' },
    { arrondissement_id: 28, name: 'Port-de-Paix' },
    { arrondissement_id: 28, name: 'Bassin-Bleu' },
    { arrondissement_id: 28, name: 'Chansolme' },
    { arrondissement_id: 28, name: 'Lapointe' },
    { arrondissement_id: 28, name: 'La Tortue' },
    { arrondissement_id: 29, name: 'Saint-Louis-du-Nord' },
    { arrondissement_id: 29, name: 'Anse-à-Foleur' },
    { arrondissement_id: 30, name: 'Archaie' },
    { arrondissement_id: 30, name: 'Cabaret' },
    { arrondissement_id: 31, name: 'Croix-des-Bouquets' },
    { arrondissement_id: 31, name: 'Cornillon' },
    { arrondissement_id: 31, name: 'Fonds-Verrettes' },
    { arrondissement_id: 31, name: 'Ganthier' },
    { arrondissement_id: 31, name: 'Thomazeau' },
    { arrondissement_id: 32, name: 'Anse-à-Galets' },
    { arrondissement_id: 32, name: 'Pointe-à-Raquette' },
    { arrondissement_id: 33, name: 'Léogâne' },
    { arrondissement_id: 33, name: 'Grand-Goâve' },
    { arrondissement_id: 33, name: 'Petit-Goâve' },
    { arrondissement_id: 34, name: 'Port-au-Prince' },
    { arrondissement_id: 34, name: 'Carrefour' },
    { arrondissement_id: 34, name: 'Cité Soleil' },
    { arrondissement_id: 34, name: 'Delmas' },
    { arrondissement_id: 34, name: 'Gressier' },
    { arrondissement_id: 34, name: 'Kenscoff' },
    { arrondissement_id: 34, name: 'Pétion-Ville' },
    { arrondissement_id: 34, name: 'Tabarre' },
    { arrondissement_id: 35, name: 'Bainet' },
    { arrondissement_id: 35, name: 'Côtes-de-Fer' },
    { arrondissement_id: 36, name: 'Belle-Anse' },
    { arrondissement_id: 36, name: 'Anse-à-Potres' },
    { arrondissement_id: 36, name: 'Grand-Gosier' },
    { arrondissement_id: 36, name: 'Thiotte' },
    { arrondissement_id: 37, name: 'Jacmel' },
    { arrondissement_id: 37, name: 'Cayes-Jacmel' },
    { arrondissement_id: 37, name: 'La Vallé' },
    { arrondissement_id: 37, name: 'Marigot' },
    { arrondissement_id: 38, name: 'Aquin' },
    { arrondissement_id: 38, name: 'Cavaillon' },
    { arrondissement_id: 38, name: 'Saint-Louis-du-Sud' },
    { arrondissement_id: 38, name: 'Fond des Blancs' },
    { arrondissement_id: 39, name: 'Les Cayes' },
    { arrondissement_id: 39, name: 'Camp-Perrin' },
    { arrondissement_id: 39, name: 'Chantal' },
    { arrondissement_id: 39, name: 'île-à-Vache' },
    { arrondissement_id: 39, name: 'Maniche' },
    { arrondissement_id: 39, name: 'Torbek' },
    { arrondissement_id: 40, name: 'Chardonnières' },
    { arrondissement_id: 40, name: 'Les Anglais' },
    { arrondissement_id: 40, name: 'Tiburon' },
    { arrondissement_id: 41, name: 'Côteaux' },
    { arrondissement_id: 41, name: 'Port-à-Piment' },
    { arrondissement_id: 41, name: 'Roche-à-Bateaux' },
    { arrondissement_id: 42, name: 'Port-Salut' },
    { arrondissement_id: 42, name: 'Arniquet' },
    { arrondissement_id: 42, name: 'Saint-Jean-du-Sud' }
  ]))
};

exports.down = function (knex, Promise) {
  return knex.schema.dropTable('communes');
};
